package com.generate.protocol

/**
 * Created by yangzhilei on 16/9/8.
 */

class Output(val protocol: Protocol) {

    val builder = StringBuilder();

    companion object {
        fun line(count: Int): String {
            val builder = StringBuilder();
            for (x in 1..count) {
                builder.append("\n")
            }
            return builder.toString();
        }

        fun tab(count: Int): String {
            val builder = StringBuilder();
            for (x in 1..count) {
                builder.append("    ");
            }
            return builder.toString();
        }
    }

    fun append(text: String): StringBuilder {
        builder.append(text);
        return builder;
    }

    fun outProtocol(): String {
        begin();
        writeField(1, "currentProductId", "long", "currentProductId")
        end();
        return builder.toString();
    }

    fun begin() {
        append("package ${protocol.packageName};${line(2)}")
        note("generated by CodeGenerate,please don't edit it...");
        append("public class ${protocol.className} extends HDAnnotationMtpProtocol {${line(2)}")
    }

    fun end() {
        append("}")
    }

    fun note(note: String) {
        append("/**\n");
        append("  $note\n");
        append(" */\n");
    }

    fun writeField(tabCount: Int, key: String, type: String, name: String) {
        append("${tab(tabCount)}@Protocol(key = \"$key\")\n")
        append("${tab(tabCount)}public $type $name;${line(2)}")
    }
}

fun main(args: Array<String>) {
    val protocol = Protocol("com.evergrande.eif.net.api.currentproduct", "HDMyCurrentProductDetailProtoAnnotation", "v1/currentproduct/op_my_current_product_detail.json", true);
    println(Output(protocol).outProtocol());
}